// flow-typed signature: 9c7cd39bebbf3ece31919d486bd5c3f4
// flow-typed version: <<STUB>>/react-social-login_v^3.4.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-social-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-social-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-social-login/dist/social-login' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-social-login/dist/social-login.js' {
  declare module.exports: $Exports<'react-social-login/dist/social-login'>;
}
