// flow-typed signature: 95349e6dab6a46740a2620263317e93d
// flow-typed version: <<STUB>>/react-app-rewire-css-modules_vcodebandits/react-app-rewire-css-modules/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-app-rewire-css-modules/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-app-rewire-css-modules/index' {
  declare module.exports: $Exports<'react-app-rewire-css-modules'>;
}
declare module 'react-app-rewire-css-modules/index.js' {
  declare module.exports: $Exports<'react-app-rewire-css-modules'>;
}
declare module 'react-app-rewire-css-modules/index.test.js' {
  declare module.exports: $Exports<'react-app-rewire-css-modules/index.test'>;
}
